[package]
name = "auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio = {version = "1.48.0", features = ["full"]}
core = {path="../../crates/core"}
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
bincode = "2.0.1"
